1.矢量内积无区别，结果是标量

In [1]:
import numpy as np

In [2]:
t1 = np. array([1,2,3])
t2 = np. array([1,2,3])
print (np. dot (t1,t2))
print (np. matmul (t1, t2))
print(t1*t2)#元素】1乘积

14
14
[1 4 9]


2.一维度与二维矩阵的乘法

In [6]:
a = np. array([1, 2, 3])
b = np.array([[1,1,1],
            [2,2,2],
            [3,3,3]])


In [7]:
np.dot(a,b)

array([14, 14, 14])

In [8]:
np.matmul(a,b)

array([14, 14, 14])

In [9]:
a*b

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

多维矩阵乘积的比较

In [10]:
m_4_4 = np.array([
                    [1,2,3,4],
                    [3,2,1,4],
                    [5,4,6,7],
                    [11,12,13, 14]
])
m_3_4_2 = np.array([
                        [[2,3],
                        [11,9],
                        [32,21],
                        [28,17]],
    
                        [[2,3],
                        [1,9],
                        [3,21],
                        [28,7]],

                        [[2,3],
                        [1,9],
                        [3,21],
                        [28,7]]
])

In [11]:
print(m_4_4.shape)
print(m_3_4_2.shape)

(4, 4)
(3, 4, 2)


# np.dot定义：

dot(a, b)[i,j,k,m]= sum(a[i,j,:]* b[k,:,m])
import numpy as np
import scipy 科学计算工具
import pandas as pd 大杀器
import sklearn 本课程前两周重点
import keras.backend as K
import tensorflow as tf

In [12]:
import sklearn

In [13]:
from sklearn import datasets
from sklearn.metrics import auc
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso

# 3.安装Tensorflow 与Keras

In [14]:
import tensorflow as tf